# Generated by Django 5.2.10 on 2026-01-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_products_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, default='Mobiles', max_length=200),
            preserve_default=False,
        ),
    ]
