# Generated by Django 5.2.10 on 2026-01-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(blank=True, default='Viooo', max_length=200),
            preserve_default=False,
        ),
    ]
