# Generated by Django 5.2.10 on 2026-01-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_choices',
            field=models.CharField(choices=[('success', 'SUCCESS'), ('failed', 'FAILED')], default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('order_placed', 'ORDER_PLACED'), ('shipped', 'SHIPPED'), ('out_for_delivery', 'OUT_FOR_DELIVERY'), ('delivered', 'DELIVERED')], default='order_placed', max_length=20),
        ),
    ]
