# Generated by Django 5.2.10 on 2026-06-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_payment_choices_alter_orders_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_choices',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('success', 'SUCCESS'), ('failed', 'FAILED'), ('pending', 'PENDING'), ('refunded', 'REFUNDED')], default='success', max_length=10),
        ),
    ]
